twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['tailwind_4_layout.html.twig']

when@test:
    twig:
        strict_variables: true
        form_themes: ['tailwind_4_layout.html.twig']
